#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Carga automáticamente las clases instaladas por Composer.
require __DIR__.'/vendor/autoload.php';

// Inicia Laravel y le entrega el comando escrito en la terminal.
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
